//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrospective.Application.API.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RetroToolEntities : DbContext, IRetrospectiveContext
    {
        public RetroToolEntities()
            : base("name=RetroToolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_mst_agiledescinfo> tbl_mst_agiledescinfo { get; set; }
        public virtual DbSet<tbl_mst_imageinfo> tbl_mst_imageinfo { get; set; }
        public virtual DbSet<tbl_mst_projectinfo> tbl_mst_projectinfo { get; set; }
        public virtual DbSet<tbl_mst_imageinfodetails> tbl_mst_imageinfodetails { get; set; }
        public virtual DbSet<tbl_mst_retroinfodetails> tbl_mst_retroinfodetails { get; set; }
        public virtual DbSet<tbl_trn_retroinfo> tbl_trn_retroinfo { get; set; }
    }
}
