//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrospective.Application.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_imageinfodetails
    {
        public int imageinfodetails_id { get; set; }
        public string imageinfodetails_text { get; set; }
        public string imageinfodetails_type { get; set; }
        public int imageinfodetails_imageinfo_id { get; set; }
        public string imageinfodetails_color { get; set; }
        public Nullable<bool> imageinfodetails_isdeleted { get; set; }
    }
}
