//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrospective.Application.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trn_retroinfo
    {
        public int retroinfo_id { get; set; }
        public string retroinfo_name { get; set; }
        public int retroinfo_projectinfo_id { get; set; }
        public string retroinfo_sprint { get; set; }
        public string retroinfo_date { get; set; }
        public string retroinfo_imagepath { get; set; }
        public int retroinfo_imageinfo_id { get; set; }
        public bool retroinfo_status { get; set; }
        public Nullable<bool> retroinfo_isdeleted { get; set; }
    }
}
