//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrospective.Application.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_agiledescinfo
    {
        public int agiledescinfo_id { get; set; }
        public string agiledescinfo_text { get; set; }
        public string agiledescinfo_type { get; set; }
        public string agiledescinfo_remarks { get; set; }
        public bool agiledescinfo_isdeleted { get; set; }
    }
}
