//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrospective.Application.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_projectinfo
    {
        public int projectinfo_id { get; set; }
        public string projectinfo_name { get; set; }
        public string projectinfo_portfolio { get; set; }
        public string projectinfo_sow_name { get; set; }
        public string projectinfo_sow_coverage { get; set; }
        public string projectinfo_remarks { get; set; }
        public bool projectinfo_isdeleted { get; set; }
    }
}
