//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrospective.Application.API.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mst_imageinfo
    {
        public int imageinfo_id { get; set; }
        public string imageinfo_name { get; set; }
        public string imageinfo_path { get; set; }
        public Nullable<bool> imageinfo_isdeleted { get; set; }
    }
}
